### ISSUE TITLE
Failing dynapcnn tests

### ISSUE THREAD

**Issue by bauerfe** [synsense/sinabs#204]
Some of the dynapcnn tests that are marked for skipping fail on my machine:

```
FAILED test_dynapcnn/test_device_movement.py::test_multi_device_movement - KeyError: 'speck2b:0'
FAILED test_dynapcnn/test_discover_device.py::test_list_all_devices - AttributeError: module 'sinabs.backend.dynapcnn.io' has no attribute 'get_all_samna_devices'
FAILED test_dynapcnn/test_discover_device.py::test_is_device_type - AttributeError: module 'sinabs.backend.dynapcnn.io' has no attribute 'get_all_samna_devices'
FAILED test_dynapcnn/test_discover_device.py::test_discover_device - KeyError: 'dvxplorer:0'
FAILED test_dynapcnn/test_large_net.py::test_to_device - KeyError: 'speck2b:0'
FAILED test_dynapcnn/test_visualizer.py::test_jit_compilation - TypeError: create_visualizer_process() got an unexpected keyword argument 'visualizer_id'
```

For a few of them it's probably just because the correct device wasn't connected. Here we might want to consider not only testing one specific device. Others failed because of a missing get_all_samna_devices function or a wrong argument to the visualizer. Those certainly need to be fixed.

**Comment by sheiksadique** [comment]
addressed in  commit bef31ce

**Comment by sheiksadique** [comment]
@bauerfe please check if the problem still exists.

**Comment by bauerfe** [comment]
The following tests still fail on my machine:
- `test_device_movement.py: test_multi_device_movement` -> specifically requires speck2b (I have a speck2f connected). Do we really want that?
- `test_discover_device.py: test_list_all_devices' -> Always raises a `NotImplementedError`. This test is designed to fail. Do we really want that?
- `test_large_net.py: test_to_device` -> Again requires Speck 2b

**Comment by bauerfe** [comment]
Also, some tests, such as `test_neuron_leak.py: test_neuron_leak_config` either take forever or cause the process to stall.

**Comment by bauerfe** [comment]
Anyways, since those tests are not intended for automated testing, let's leave it as it is for now until the next overhauls of the test pipeline.
